version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    ports:
      - 6080:8080
      - 6081:8081
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - /srv/data/media/books:/books
      - /srv/calibre/library:/library
    restart: unless-stopped

networks:
  default:
    name: boulder
