version: "3"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    ports:
      - 7575:7575
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Stockholm
    volumes:
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
    restart: unless-stopped

networks:
  default:
    name: boulder
