version: "3"
services:

    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        ports:
            - 8080:8080 # qBittorrent Web UI
            - 6881:6881 # qBittorrent
            - 6881:6881/udp # qBittorrent
            - 8888:8888/tcp # HTTP proxy
            - 8388:8388/tcp # Shadowsocks
            - 8388:8388/udp # Shadowsocks
        environment:
            - VPN_SERVICE_PROVIDER=mullvad
            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY=<private-key>
            - WIREGUARD_ADDRESSES=<wireguard-addresses>/32
            - SERVER_CITIES=<server-cities>
            - TZ=Europe/Stockholm
            - FIREWALL_OUTBOUND_SUBNETS=<local-ip-subnet>/24
            - DOT=off
        volumes:
             - ./gluetun:/gluetun

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
            - WEBUI_PORT=8080
        volumes:
            - ./qbittorrent:/config
            - /library/torrents:/library/torrents
        network_mode: 'service:gluetun'
        depends_on:
            - gluetun

networks:
  default:
    name: <network-name>
