version: "3"
services:
    joplin:
        container_name: joplin
        image: joplin/server:latest
        ports:
            - 22300:443
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=Europe/Stockholm
            - APP_PORT=443
            - APP_BASE_URL=https://<subdomain>.<domain>.<tld>/
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=<pg-password>
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=joplin-db
        restart: unless-stopped
        depends_on:
            - joplin-db

    joplin-db:
        container_name: joplin-db
        image: postgres:15
        ports:
            - 5432:5432
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=Europe/Stockholm
            - POSTGRES_PASSWORD=<pg-password>
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        restart: unless-stopped

networks:
  default:
    name: <network-name>
