version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - TZ=Europe/Stockholm
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * * # run daily at 4 am
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://<subdomain>.<domain>.<tld>
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=<token>
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: watchtower ddns-updater nginx_proxy_manager jellyfin gluetun qbittorrent prowlarr radarr sonarr bazarr jellyseerr freshrss joplin joplin-db calibre calibre-web

networks:
  default:
    name: <network-name>
