version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - TZ=Europe/Stockholm
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 30 4 * * * # run daily at 4:30 am
      - WATCHTOWER_NOTIFICATION_URL=gotify://sub.domain.tld/<gotify-token>/
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: <service_1> <service_2> <service_3>

networks:
  default:
    name: gravel
    external: true